server:
  port: 9001

spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: false # 表示是否将自己注册进eurekaServer 默认为true
    fetch-registry: true # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点为所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:9001/eureka,http://localhost:9002/eureka
  instance:
    prefer-ip-address: true # eureka页面展示具体ip